name: xarray-101
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - ipyleaflet
  - nodejs
  - holoviews
  - hvplot
  - geoviews
  - geopandas  
  - pandas
  - xarray
  - rioxarray
  - datashader
  - intake
  - intake-geopandas
  - intake-xarray
  - matplotlib
  - s3fs
  
